# Generated by Django 6.1.1 on 2026-10-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_confirmed_booking_per_event_seat',
        ),
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_seat_per_venue',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='amenities',
            field=models.CharField(blank=True, default='AC, Charging Point, Reading Light, Water Bottle, WiFi', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='boarding_point',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='bus_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='bus_type',
            field=models.CharField(blank=True, default='AC Sleeper (2+1)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.CharField(blank=True, default='Chennai', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='dropping_point',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, default='Bangalore', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.seat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
