# Generated by Django 6.1.1 on 2026-10-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at'], 'verbose_name': 'Bus Ticket Booking', 'verbose_name_plural': 'Bus Ticket Bookings'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Bus Trip', 'verbose_name_plural': 'Bus Trips'},
        ),
    ]
