# Generated by Django 6.1.1 on 2026-10-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this user/operator is approved to log in.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OPERATOR', 'Bus Operator'), ('ORGANIZER', 'Bus Operator (Legacy)'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20),
        ),
    ]
