# Generated by Django 6.1.1 on 2026-10-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_approval_status_user_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OPERATOR', 'Bus Operator'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20),
        ),
    ]
