# Generated by Django 6.1.1 on 2026-10-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizerprofile',
            options={'verbose_name': 'Bus Operator Profile', 'verbose_name_plural': 'Bus Operator Profiles'},
        ),
    ]
